openapi: 3.0.1
info:
    title: web-sum ChatGPT Plugin
    description: A plugin that allows the user to enter a webpage and have ChatGPT summarize it.
    version: "v1.0.0"
servers:
    - url: https://web-sum.sunnyson.repl.co
paths:
    /summarize:
        post:
            operationId: summarize
            summary: Summarize a webpage
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                url:
                                    type: string
                                    description: The URL of the webpage to summarize.
            responses:
                "200":
                    description: OK
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    summary:
                                        type: string
                                        description: The summary of the webpage.